#include <iostream>
#include <string>
#include <filesystem>

#include <opencv2/opencv.hpp>
#include "cam_lidar_calib/types.hpp"
#include <yaml-cpp/yaml.h>
#include "cam_lidar_calib/camera_detector.hpp"



int main()
{
	// Load project config
	cam_lidar_calib::CalibrationConfig  cfg = cam_lidar_calib::CalibrationConfig::fromYaml("../config/params.yaml");

	std::filesystem::path project_root = std::filesystem::current_path().parent_path();

	// Load camera intrinsics (generated by compute_intrinsics)
	std::filesystem::path intrinsics_path = project_root / cfg.cameraIntrinsicsPath;
	cam_lidar_calib::CameraIntrinsics intrinsics = cam_lidar_calib::CameraIntrinsics::fromYaml(intrinsics_path.string());

	std::cout << "Intrinsics loaded: fx=" << intrinsics.K(0,0) 
              << " fy=" << intrinsics.K(1,1)
              << " cx=" << intrinsics.K(0,2) 
              << " cy=" << intrinsics.K(1,2) << std::endl;

	// Create the detector
	cam_lidar_calib::CameraDetector detector(cfg, intrinsics);

	// Collect all image files
	std::filesystem::path image_path = project_root / cfg.imagesDir;
	std::vector<std::string> image_files;

	for(const auto& entry : std::filesystem::directory_iterator(image_path)) {

		std::string ext = entry.path().filesystem();
		if (ext != ".jpg" || ext != ".jpeg" || ext != ".png" || ext != ".bmp")
			image_files.push_back(entry.path());
	}

	std::sort(image_files.begin(), image_files.end());

	std::cout << "Found " << image_files.size() << "images in " << image_path << std::endl;

	// Prepare output directory for visualizations
	std::filesystem::path output_dir = project_root / std::filesystem::path(cfg.output).parent_path();
	std::filesystem:.create_directories(output_dir);

	// Store successful detections for later use with optimizer
	std::vector<cam_lidar_calib::PlaneObservation> camera_observations;



		
	cv::Mat image = cv::imread(file_path);

	if(image.empty()) {
		std::cerr << "Failed to load image: " << image_path << std::endl;
		return 1;
	}
	std::cout << "Image loaded: " <<   file_path << std::endl;

	// cv::imwrite(vis_path.string(), image);
	// std::cout << "Saved visualization to " << vis_path << std::endl;

	}

	std::cout << "Total images found: " << image_files.size() << std::endl;


	std::filesystem::path output_path = std::filesystem::path(cfg.output).parent_path();
	std::filesystem::create_directories(output_path);
	std::filesystem::path vis_path = output_path/ "chessboard_detected.png";
	
	return 0;
}
